More fixes to GitHub Actions (#4106)
* More fixes to GitHub Actions

* report code coverage from GH Actions

* add token

* try again

* add comment about codecov failures

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -56,17 +56,18 @@ jobs:
       run: |
         make test-with-cov
 
-    # TODO: remove codecov report publishing from TeamCity build and then uncomment this:
-    # - name: Upload coverage to Codecov
-    #   if: matrix.python == '3.7'
-    #   run: |
-    #     # Ignore codecov failures as the codecov server is not
-    #     # very reliable but we don't want to report a failure
-    #     # in the github UI just because the coverage report failed to
-    #     # be published.
-    #     codecov || echo "codecov upload failed"
-    #   env:
-    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+    - name: Upload coverage to Codecov
+      if: matrix.python == '3.7'
+      env:
+        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+      run: |
+        # Ignore codecov failures as the codecov server is not
+        # very reliable but we don't want to report a failure
+        # in the github UI just because the coverage report failed to
+        # be published.
+        # This will also fail for forked repositories since the secret token won't
+        # be available.
+        codecov -t $CODECOV_TOKEN || echo "codecov upload failed"
 
   models:
     runs-on: ubuntu-latest
