move everything to single workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,20 +1,128 @@
-name: Release
+name: CI
 
 on:
+  # TODO: add nightly schedule.
+  pull_request:
+    branches:
+    - master
   push:
     branches:
     - master
   release:
     types: [published]
-  # TODO: add nightly schedule.
-  # TODO: remove this 'pull_request' trigger.
-  pull_request:
-    branches:
-    - master
 
 jobs:
-  # Builds the PyPI distribution files.
-  build:
+  check_core:
+    name: Check Core
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python: ['3.6', '3.7']
+
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Setup Python
+      uses: actions/setup-python@v1
+      with:
+        python-version: ${{ matrix.python }}
+
+    - uses: actions/cache@v1
+      with:
+        path: ${{ env.pythonLocation }}
+        key: ${{ runner.os }}-pydeps-${{ matrix.python }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
+        restore-keys: |
+          ${{ runner.os }}-pydeps-${{ matrix.python }}
+
+    - name: Install requirements
+      run: |
+        pip install --upgrade pip setuptools wheel
+        pip install -e .
+        pip install --upgrade -r dev-requirements.txt
+
+    - name: Debug info
+      run: |
+        pip freeze
+
+    - name: Lint
+      run: |
+        make lint
+
+    - name: Type check
+      run: |
+        make typecheck
+
+    - name: Run tests
+      run: |
+        make test-with-cov
+
+    - name: Upload coverage to Codecov
+      if: matrix.python == '3.7'
+      env:
+        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+      run: |
+        # Ignore codecov failures as the codecov server is not
+        # very reliable but we don't want to report a failure
+        # in the github UI just because the coverage report failed to
+        # be published.
+        # This will also fail for forked repositories since the secret token won't
+        # be available.
+        codecov -t $CODECOV_TOKEN || echo "codecov upload failed"
+
+  check_models:
+    name: Check Models
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python: ['3.6', '3.7']
+
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Setup Python
+      uses: actions/setup-python@v1
+      with:
+        python-version: ${{ matrix.python }}
+
+    - uses: actions/cache@v1
+      with:
+        path: ${{ env.pythonLocation }}
+        key: ${{ runner.os }}-pydeps-${{ matrix.python }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
+        restore-keys: |
+          ${{ runner.os }}-pydeps-${{ matrix.python }}
+
+    - name: Install requirements
+      run: |
+        pip install --upgrade pip setuptools wheel
+        pip install -e .
+        pip install --upgrade -r dev-requirements.txt
+
+    - name: Debug info
+      run: |
+        pip freeze
+
+    - name: Pull and install models repo
+      env:
+        EXCLUDE_ALLENNLP_IN_SETUP: "true"
+      run: |
+        git clone https://github.com/allenai/allennlp-models.git
+        cd allennlp-models && pip install -e . && pip install -r dev-requirements.txt
+
+    - name: Run models tests
+      run: |
+        cd allennlp-models && make test
+
+    - name: Clean up
+      run: |
+        # Don't want this in the cache since the other workflow uses same cache.
+        pip uninstall --yes allennlp_models
+
+  # Builds package distribution files for PyPI.
+  build_package:
+    name: Build Package
+    # TODO: uncomment these lines
+    # needs: [check_core, check_models]
+    # if: github.event_name != 'pull_request'
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -41,22 +149,10 @@ jobs:
         pip install -e .
         pip install --upgrade -r dev-requirements.txt
 
-    - name: Pull and install models repo
-      env:
-        EXCLUDE_ALLENNLP_IN_SETUP: "true"
-      run: |
-        git clone https://github.com/allenai/allennlp-models.git
-        cd allennlp-models && pip install -e . && pip install -r dev-requirements.txt
-
     - name: Build core package
       run: |
         echo "Building packages for core release"
         python setup.py bdist_wheel sdist
-
-    - name: Build models package
-      run: |
-        echo "Building packages for models release"
-        cd allennlp-models && python setup.py bdist_wheel sdist
 
     - name: Save core package
       uses: actions/upload-artifact@v1
@@ -64,28 +160,18 @@ jobs:
         name: core-package
         path: dist
 
-    - name: Save models package
-      uses: actions/upload-artifact@v1
-      with:
-        name: models-package
-        path: allennlp-models/dist
-
-    - name: Clean up
-      run: |
-        # Don't want this in the cache since the other workflow uses same cache.
-        pip uninstall --yes allennlp_models
-
   # Tests installing from the distribution files.
-  test:
-    needs: [build]
+  test_package:
+    name: Test Package
+    needs: [build_package]
+    # TODO: uncomment
+    # if: github.event_name != 'pull_request'
     runs-on: ubuntu-latest
     strategy:
       matrix:
         python: ['3.6', '3.7']
 
     steps:
-    - uses: actions/checkout@v2
-
     - name: Setup Python
       uses: actions/setup-python@v1
       with:
@@ -101,19 +187,9 @@ jobs:
         name: core-package
         path: dist
 
-    - name: Download models package
-      uses: actions/download-artifact@v1
-      with:
-        name: models-package
-        path: allennlp-models/dist
-
     - name: Install core package
       run: |
         pip install $(ls dist/*.whl)
-
-    - name: Install models package
-      run: |
-        cd allennlp-models && pip install $(ls dist/*.whl)
 
     - name: Test install
       run: |
@@ -121,7 +197,10 @@ jobs:
 
   # Builds Docker image from the core distribution files and uploads to Docker Hub.
   docker:
-    needs: [build, test]
+    name: Docker
+    needs: [build_package, test_package]
+    # TODO: uncomment
+    # if: github.event_name != 'pull_request'
     runs-on: ubuntu-latest
 
     steps:
@@ -150,23 +229,29 @@ jobs:
         docker run --rm allennlp test-install
 
     - name: Upload master image
-      if: github.event_name == 'push'
+      # Only run this for pushes to master on the main repo, not forks.
+      if: github.repository == 'allenai/allennlp' && github.event_name == 'push'
       run: |
         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
         docker tag allennlp allennlp/commit:$GITHUB_SHA
         docker push allennlp/commit:$GITHUB_SHA
 
     - name: Upload release image
-      if: github.event_name == 'release'
+      # Only run this for releases on the main repo, not forks.
+      if: github.repository == 'allenai/allennlp' && github.event_name == 'release'
       run: |
         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
         TAG=${GITHUB_REF/refs\/tags\//};
         docker tag allennlp allennlp/allennlp:$TAG
         docker push allennlp/allennlp:$TAG
 
-  # Builds the API documentation and pushes it to the appropriate folder in the allennlp-docs repo.
+  # Builds the API documentation and pushes it to the appropriate folder in the
+  # allennlp-docs repo.
   docs:
-    needs: [build, test]
+    name: Docs
+    needs: [build_package, test_package]
+    # TODO: uncomment
+    # if: github.event_name != 'pull_request'
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -202,6 +287,9 @@ jobs:
         ./scripts/build_docs.sh
 
     - name: Deploy docs
+      # TODO: uncomment these lines.
+      # # Only run this on main repo, not forks.
+      # if: github.repository == 'allenai/allennlp'
       env:
         DOCS_DEPLOY_KEY: ${{ secrets.DOCS_DEPLOY_KEY }}
       run: |
@@ -245,10 +333,10 @@ jobs:
         # TODO: uncomment this.
         # GIT_SSH_COMMAND='ssh -i ~/.ssh/allennlp-docs.key' git push
 
-  # Publish the distribution files to PyPI for both core and models.
+  # Publish the core distribution files to PyPI.
   publish:
     if: github.repository == 'allenai/allennlp' && github.event_name == 'release'
-    needs: [build, test, docker, docs]
+    needs: [build_package, test_package, docker, docs]
     # Only publish on "allenai/allennlp", and not forks.
     runs-on: ubuntu-latest
 
@@ -270,22 +358,6 @@ jobs:
         name: core-package
         path: dist
 
-    - name: Download models package
-      uses: actions/download-artifact@v1
-      with:
-        name: models-package
-        path: allennlp-models/dist
-
     - name: Publish core package
-      env:
-        PYPI_USERNAME: allennlp
-        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
       run: |
-        twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
-
-    - name: Publish models package
-      env:
-        PYPI_USERNAME: allennlp
-        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
-      run: |
-        twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD allennlp-models/dist/*
+        twine upload -u allennlp -p ${{ secrets.PYPI_PASSWORD }} dist/*
